version: "3"
services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
      args:
        - env=production
    container_name: spring-boot-angular-nginx
    ports:
      - 80:80
